name: ci

on:
  push:
    branches: ["main"]
    tags: ["!release/**"]
  pull_request:
    branches: ["main"]

permissions: write-all

jobs:
  deno:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - uses: denoland/setup-deno@v1

      - name: Build (Rust)
        run: deno task wasmbuild

      # - name: Lint
      #   run: deno lint

      - name: Test
        run: deno test -A

      - name: Build (Deno)
        run: deno task build

      - name: Push to build branch and release if tag
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: deno task libpack publish --build-branch=build --release-tag-prefix=release/
